package q2_Even_Fibonacci_numbers

/**
 * Even Fibonacci numbers
 * Problem 2
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2,  * the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the  * even-valued terms.
 */
object Q2 {
    @JvmStatic
    fun main(args: Array<String>) {
        //short Fibonacci(0)=1 -> f(0)=1
        //so f(0)=1,f(1)=1,f(2)=2,f(3)=3,f(4)=5,...
        //so sumOfF(0)=f(0)=1,sumOfF(1)=f(0)+f(1)=2,...
        //what we needed is sumOfF(n);f(n)<=400,0000 && f(n+1)>400,0000;
    }
}